  version: '3'
  services:
    ghost:
      image: ghost:1-alpine
      ports:
        - 2368:2368
      depend_on:
        - "db"
      environment:
        database__client: mysql
        database__connection__database: ghost 
        database__connection__host: db
        database__connection__user: trybe
        database__connection__password: trybe
    db:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD="trybe"    
